### ISSUE TITLE
CTestAdapter with VS2017 CMake project support looks for tests in source dir instead of binary dir

### ISSUE THREAD

**Issue by puetzk** [micst/CTestTestAdapter#3]
When using the new VS2017 15.3 built-in [CMake project support](https://blogs.msdn.microsoft.com/vcblog/2017/09/14/cmake-support-in-visual-studio-cmake-3-9-linux-targeting-feedback/), BuildConfiguration.SolutionDir returns the returns the folder containing the CMakeLists.txt, since there is no .sln file. This eventually causes CTestContainerDiscoverer.UpdateListOfValidTests to use the wrong working dir for its `ctest -N` call, and thus to discover no tests (because the CTestTestfile.cmake files are in the binary dir, not the source dir).

This is different than using the CMake "Visual Studio..." generator, where CMake generates .vcxproj and .sln files, because in that case the generated solution file is in the CMAKE_BINARY_DIR.

**Comment by micst** [comment]
I moved development of the Test Adapter to a new github project, an issue corresponding to this one was created [here](https://github.com/micst/CTestAdapter/issues/1).
