### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by toeb** [micst/CTestTestAdapter#7]
Hi -  sorry there is no PM in github so I had to create an issue here ;)  

I saw that you created CTestAdapter.  (also ctesttestadapter was a mouthful - even though more consistent - I thought about CTestAdapter as well but found it too ambiguous - mistake ) It looks very good :)   and thanks for the credits.  

I see the project uses CMake to add dotnet projects and I have a couple of questions because I might want to add some stuff to [cmakepp](https://github.com/toeb/cmakepp) to make dotnet/CMake easier

* Did you think of  the CMake code to create these projects yourself and/or do you have resources for dotnet/CMake.

* Does using CMake and dotnet work well? (in comparison to normal visual studio csproj) or are major features missing normally available in VS?

* Why did you do it?  (cross platfrom dotnet build / multitarget version (VS10-15) or just because you like cmake?

If you could elabarate it would be greatly appreciated

**Comment by micst** [comment]
Hi @toeb , I was just about to archive this repo when I saw your new comment here :-). I actually would like to move this discussion to `CTestAdapter` so I don't have to check two sources for one purpose. I'll open an issue in the new project with your content and put my answers there.
